---
- name: Import IPtables Rule NRPE
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 5666
    action: insert
    comment: "Nagios NRPE Port"
    jump: ACCEPT
  become: yes

- name: Save IPtables
  shell: iptables-save > /etc/sysconfig/iptables
  become: yes

- name: Reload IPtables
  systemd:
    state: reloaded
    name: iptables
  become: yes
...