---
- name: Import Pre Check Tasks
  import_tasks: pre_checks.yml

- name: Shutdown Main Application(s)
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ application | default([]) }}"
  when: item not in ["everseen", "wms"]
  notify: Start Main Application(s)

- name: Shutdown Everseen, if Everseen Server
  shell:
    cmd: ~/everseen.sh stop
  become: yes
  become_user: podman-svc
  when: application == "everseen"

- name: Shutdown WMS apps, if WMS Server
  import_tasks: wms.yml
  when: application == "wms"

- name: Import Update Tasks
  import_tasks: update.yml
...
