---
##### Chariton PROD Servers #####
- name: Chariton - Stopping GRO
  shell: 
    cmd: "/opt/hy-vee/scripts/gro/gro stop"
  become: yes
  become_user: "{{ admin_user }}"
  when: "'wms_prod_chr_app' in group_names or 'wms_dev_chr_app' in group_names"

- name: Chariton - Stopping HBC
  shell: 
    cmd: "/opt/hy-vee/scripts/hbc/hbc stop"
  become: yes
  become_user: "{{ admin_user }}"
  when: "'wms_prod_chr_app' in group_names or 'wms_dev_chr_app' in group_names"

- name: Chariton - Stopping PER
  shell: 
    cmd: "/opt/hy-vee/scripts/per/per stop"
  become: yes
  become_user: "{{ admin_user }}"
  when: "'wms_prod_chr_app' in group_names or 'wms_dev_chr_app' in group_names"

##### All Other Warehouse Servers #####
- name: Stopping DB
  shell: 
    cmd: "{{ manh_home }}/{{ db_name }}/.sd/stop.sh"
  become: yes
  become_user: "{{ admin_user }}"
  when: 
    - "'wms_prod_chr_app' not in group_names and 'wms_dev_chr_app' not in group_names"
    - db_name != "null"

- name: Stopping LM
  shell: 
    cmd: "{{ manh_home }}/{{ lm_name }}/.sd/stop.sh"
  become: yes
  become_user: "{{ admin_user }}"
  when:
    - "'wms_prod_chr_app' not in group_names and 'wms_dev_chr_app' not in group_names" 
    - lm_name != "null"

- name: Stopping WM
  shell: 
    cmd: "{{ manh_home }}/{{ wm_name }}/.sd/stop.sh"
  become: yes
  become_user: "{{ admin_user }}"
  when: "'wms_prod_chr_app' not in group_names and 'wms_dev_chr_app' not in group_names"

- name: Stopping MDA
  shell: 
    cmd: "{{ manh_home }}/{{ mda_name }}/.sd/stop.sh"
  become: yes
  become_user: "{{ admin_user }}"
  when: "'wms_prod_chr_app' not in group_names and 'wms_dev_chr_app' not in group_names"

- name: Stopping MIP
  shell: 
    cmd: "{{ manh_home }}/{{ mip_name }}/.sd/stop.sh"
  become: yes
  become_user: "{{ admin_user }}"
  when: "'wms_prod_chr_app' not in group_names and 'wms_dev_chr_app' not in group_names"
...
