#!/bin/bash
set -x

ENVIRONMENT="${1,,}"
SYSTEM="${2,,}"
SUBSYSTEM="${3,,}"

# Local debugging
# ENVIRONMENT="$1"
# SYSTEM="$2"
# SUBSYSTEM="$3"

export ANSIBLE_CONFIG="etc/ansible.cfg"

test -s ./ansible/etc/vault_pass.txt
vpassRC=$(echo $?)

hostname -f
pwd

if [ "$vpassRC" -eq "0" ]; then
  echo "Info: Vault password file is populated"
elif [ "$vpassRC" -eq "1" ]; then
  echo "Error: Vault password file is empty"
else
  echo "Warning: Not sure what you did but, you should probably stop."
fi

if [ -z $SUBSYSTEM ]; then
  LIMIT="${SYSTEM}_${ENVIRONMENT}"
else
  LIMIT="${SYSTEM}_${ENVIRONMENT}_${SUBSYSTEM}"
fi

if [ "$ENVIRONMENT" == "prod" ]; then
  export ANSIBLE_INVENTORY="inventories/production/"
elif [ "$ENVIRONMENT" == "dev" ];  then
  export ANSIBLE_INVENTORY="inventories/development/hosts"
elif [ "$ENVIRONMENT" == "qa" ]; then
  export ANSIBLE_INVENTORY="inventories/qa/hosts"
else
  export ANSIBLE_INVENTORY="inventories/hosts"
fi

pushd ansible
ansible-playbook site.yml -u ansible -l $LIMIT --diff
popd
