---
- name: Capture Snapshot for Nagios VM
  win_shell: |
    $nagVM = Get-VM | Where-Object VMName -Like "*Nagios*" | Where-Object ReplicationMode -ne "Replica"
    $preAnsNagUpChks =  $nagVM | Get-VMSnapshot
    if ($null -eq $preAnsNagUpChks) {
      $nagVM | Checkpoint-VM -SnapshotName "{{ snapshot_name }}"
    }
  delegate_to: "{{ vm_host }}"
...