---
galaxy_info:
  author: Andrew Wickham
  description: Install, configure, and enforce auditd
  license: MIT
  platforms:
  - name: RedHat
  - name: CentOS
  - name: SUSE
  - name: Debian
  categories:
  - system
...