---
- name: Reboot Server
  reboot:
    msg: "Rebooting after applying OS updates"
    reboot_timeout: 3600
  throttle: 1

- name: Start Main Application(s)
  systemd:
    name: "{{ item }}"
    state: started
  with_items: "{{ application }}"
  when: item not in ["everseen", "wms"]

- name: Start WMS apps, if WMS Server
  import_tasks: wms.yml
  when: application == "wms"

- name: Import Post Check Tasks
  import_tasks: post_checks.yml
...