#!/bin/bash

export ANSIBLE_CONFIG="etc/ansible.cfg"
export ANSIBLE_HOST_KEY_CHECKING=False
export ANSIBLE_VAULT_KEY=etc/ansible_vault_key.txt

if [ -d "./venv" ]; then
  echo "Virtual Python Environment Found"
  source ./venv/bin/activate
else
  echo "Error: execute 'make setup' before this step"
  exit 1
fi

array=(stage dev qa prod)

select choice in "${array[@]}"; do
    [[ -n $choice ]] || { echo "Invalid choice. Please try again." >&2; continue; }
    ENVIRONMENT="$choice"
    break
done

if [ $ENVIRONMENT = "stage" ]; then
  export ANSIBLE_INVENTORY="inventories/staging/hosts"
elif [ $ENVIRONMENT = "dev" ]; then
  export ANSIBLE_INVENTORY="inventories/development/hosts"
elif [ $ENVIRONMENT = "qa" ]; then
  export ANSIBLE_INVENTORY="inventories/qa/hosts"
elif [ $ENVIRONMENT = "prod" ]; then
  export ANSIBLE_INVENTORY="inventories/production/"
else
  export ANSIBLE_INVENTORY="inventories/hosts"
fi

pushd ansible
if [ "$1" == "-c" ]; then
  ansible-playbook site.yml --diff -u ansible --check
else
  ansible-playbook site.yml --diff -u ansible
fi
popd
