---
- name: Set downtime
  nagiosctl:
    address: https://datacenterops.hy-vee.net
    apikey: "{{ vault_nagios_gk_svc }}"
    action: set-downtime
    duration: "{{ downtime_duration | int }}"
    host: "{{ inventory_hostname }}"
    comment: "{{ comment }}"
    verify: false
  delegate_to: localhost
  become: False
...
