---
- hosts: all
  gather_facts: true
  pre_tasks:
    - name: Check if we are a database server
      set_fact:
        is_db_server: "{{ inventory_hostname is match('.*db.*') }}"

- hosts: all
  gather_facts: false
  pre_tasks:
  - name: Skip if we are a database server
    meta: end_play
    when: is_db_server
  roles:
    - role: snapshot
  vars: 
    input: add
    snapshot_name: "patching"
    snapshot_description: "before patching"

- hosts: all
  gather_facts: false
  vars:
    downtime_duration: 90
    comment: "patching"
  roles:
    - role: downtime

- hosts: all
  serial: 1
  gather_facts: false
  roles:
    - role: linux_patching
  become_user: root
  become: true
...